using System.Collections.Generic;

namespace ConsoleApp2
{
    public class SystemTimezoneOptionInfo
    {
        private readonly short _timezoneId;
        private readonly string _olsonName;
        private readonly string _displayName;
        private readonly string _countryCode;
        private readonly string _standardAbbr;
        private readonly string _daylightAbbr;

        public short TimezoneId
        {
            get { return _timezoneId; }
        }

        public string OlsonName
        {
            get { return _olsonName; }
        }

        public string DisplayName
        {
            get { return _displayName; }
        }

        public string CountryCode
        {
            get { return _countryCode; }
        }

        public string StandardAbbr
        {
            get { return _standardAbbr; }
        }

        public string DaylightAbbr
        {
            get { return _daylightAbbr; }
        }

        private static readonly IList<SystemTimezoneOptionInfo> _timeZones = new List<SystemTimezoneOptionInfo>()
        {
            new SystemTimezoneOptionInfo(1, "Africa/Abidjan", "(GMT+00:00) Abidjan", "CI", "GMT", null),
            new SystemTimezoneOptionInfo(2, "Africa/Accra", "(GMT+00:00) Accra", "GH", "GMT", "GHST"),
            new SystemTimezoneOptionInfo(3, "Africa/Addis_Ababa", "(GMT+03:00) Addis Ababa", "ET", "EAT", null),
            new SystemTimezoneOptionInfo(4, "Africa/Algiers", "(GMT+01:00) Algiers", "DZ", "CET", "WEST"),
            new SystemTimezoneOptionInfo(5, "Africa/Asmara", "(GMT+03:00) Asmera", "ER", "EAT", null),
            new SystemTimezoneOptionInfo(6, "Africa/Asmera", null, null, "EAT", null),
            new SystemTimezoneOptionInfo(7, "Africa/Bamako", "(GMT+00:00) Bamako", "ML", "GMT", null),
            new SystemTimezoneOptionInfo(8, "Africa/Bangui", "(GMT+01:00) Bangui", "CF", "WAT", null),
            new SystemTimezoneOptionInfo(9, "Africa/Banjul", "(GMT+00:00) Banjul", "GM", "GMT", null),
            new SystemTimezoneOptionInfo(10, "Africa/Bissau", "(GMT+00:00) Bissau", "GW", "GMT", null),
            new SystemTimezoneOptionInfo(11, "Africa/Blantyre", "(GMT+02:00) Blantyre", "MW", "CAT", null),
            new SystemTimezoneOptionInfo(12, "Africa/Brazzaville", "(GMT+01:00) Brazzaville", "CD", "WAT", null),
            new SystemTimezoneOptionInfo(13, "Africa/Bujumbura", "(GMT+02:00) Bujumbura", "BI", "CAT", null),
            new SystemTimezoneOptionInfo(14, "Africa/Cairo", "(GMT+02:00) Cairo", "EG", "EET", "EEST"),
            new SystemTimezoneOptionInfo(15, "Africa/Casablanca", "(GMT+00:00) Casablanca", "MA", "WET", "WEST"),
            new SystemTimezoneOptionInfo(16, "Africa/Ceuta", "(GMT+01:00) Ceuta", "ES", "CET", "CEST"),
            new SystemTimezoneOptionInfo(17, "Africa/Conakry", "(GMT+00:00) Conakry", "GN", "GMT", null),
            new SystemTimezoneOptionInfo(18, "Africa/Dakar", "(GMT+00:00) Dakar", "SN", "GMT", null),
            new SystemTimezoneOptionInfo(19, "Africa/Dar_es_Salaam", "(GMT+03:00) Dar es Salaam", "TZ", "EAT", null),
            new SystemTimezoneOptionInfo(20, "Africa/Djibouti", "(GMT+03:00) Djibouti", "DJ", "EAT", null),
            new SystemTimezoneOptionInfo(21, "Africa/Douala", "(GMT+01:00) Douala", "CM", "WAT", null),
            new SystemTimezoneOptionInfo(22, "Africa/El_Aaiun", "(GMT+00:00) El Aaiun", "EH", "WET", "WEST"),
            new SystemTimezoneOptionInfo(23, "Africa/Freetown", "(GMT+00:00) Freetown", "SL", "GMT", "SLST"),
            new SystemTimezoneOptionInfo(24, "Africa/Gaborone", "(GMT+02:00) Gaborone", "BW", "CAT", "CAST"),
            new SystemTimezoneOptionInfo(25, "Africa/Harare", "(GMT+02:00) Harare", "ZW", "CAT", null),
            new SystemTimezoneOptionInfo(26, "Africa/Johannesburg", "(GMT+02:00) Johannesburg", "ZA", "SAST", "SAST"),
            new SystemTimezoneOptionInfo(27, "Africa/Juba", "(GMT+03:00) Juba", "SS", "EAT", "CAST"),
            new SystemTimezoneOptionInfo(28, "Africa/Kampala", "(GMT+03:00) Kampala", "UG", "EAT", null),
            new SystemTimezoneOptionInfo(29, "Africa/Khartoum", "(GMT+03:00) Khartoum", "SD", "EAT", "CAST"),
            new SystemTimezoneOptionInfo(30, "Africa/Kigali", "(GMT+02:00) Kigali", "RW", "CAT", null),
            new SystemTimezoneOptionInfo(31, "Africa/Kinshasa", "(GMT+01:00) Kinshasa", "CG", "WAT", null),
            new SystemTimezoneOptionInfo(32, "Africa/Lagos", "(GMT+01:00) Lagos", "NG", "WAT", null),
            new SystemTimezoneOptionInfo(33, "Africa/Libreville", "(GMT+01:00) Libreville", "GA", "WAT", null),
            new SystemTimezoneOptionInfo(34, "Africa/Lome", "(GMT+00:00) Lome", "TG", "GMT", null),
            new SystemTimezoneOptionInfo(35, "Africa/Luanda", "(GMT+01:00) Luanda", "AO", "WAT", null),
            new SystemTimezoneOptionInfo(36, "Africa/Lubumbashi", "(GMT+02:00) Lubumbashi", "CG", "CAT", null),
            new SystemTimezoneOptionInfo(37, "Africa/Lusaka", "(GMT+02:00) Lusaka", "ZM", "CAT", null),
            new SystemTimezoneOptionInfo(38, "Africa/Malabo", "(GMT+01:00) Malabo", "GQ", "WAT", null),
            new SystemTimezoneOptionInfo(39, "Africa/Maputo", "(GMT+02:00) Maputo", "MZ", "CAT", null),
            new SystemTimezoneOptionInfo(40, "Africa/Maseru", "(GMT+02:00) Maseru", "LS", "SAST", "SAST"),
            new SystemTimezoneOptionInfo(41, "Africa/Mbabane", "(GMT+02:00) Mbabane", "SZ", "SAST", null),
            new SystemTimezoneOptionInfo(42, "Africa/Mogadishu", "(GMT+03:00) Mogadishu", "SO", "EAT", null),
            new SystemTimezoneOptionInfo(43, "Africa/Monrovia", "(GMT+00:00) Monrovia", "LR", "GMT", null),
            new SystemTimezoneOptionInfo(44, "Africa/Nairobi", "(GMT+03:00) Nairobi", "KE", "EAT", null),
            new SystemTimezoneOptionInfo(45, "Africa/Ndjamena", "(GMT+01:00) Ndjamena", "TD", "WAT", "WAST"),
            new SystemTimezoneOptionInfo(46, "Africa/Niamey", "(GMT+01:00) Niamey", "NE", "WAT", null),
            new SystemTimezoneOptionInfo(47, "Africa/Nouakchott", "(GMT+00:00) Nouakchott", "MR", "GMT", null),
            new SystemTimezoneOptionInfo(48, "Africa/Ouagadougou", "(GMT+00:00) Ouagadougou", "BF", "GMT", null),
            new SystemTimezoneOptionInfo(49, "Africa/Porto-Novo", "(GMT+01:00) Porto-Novo", "BJ", "WAT", null),
            new SystemTimezoneOptionInfo(50, "Africa/Sao_Tome", "(GMT+00:00) Sao Tome", "ST", "GMT", null),
            new SystemTimezoneOptionInfo(51, "Africa/Tripoli", "(GMT+02:00) Tripoli", "LY", "EET", "CEST"),
            new SystemTimezoneOptionInfo(52, "Africa/Tunis", "(GMT+01:00) Tunis", "TN", "CET", "CEST"),
            new SystemTimezoneOptionInfo(53, "Africa/Windhoek", "(GMT+01:00) Windhoek", "NA", "WAT", "WAST"),
            new SystemTimezoneOptionInfo(54, "America/Anchorage", "(GMT-09:00) Alaska Time", "US", "AKST", "AKDT"),
            new SystemTimezoneOptionInfo(55, "America/Anguilla", "(GMT-04:00) Anguilla", "AI", "AST", null),
            new SystemTimezoneOptionInfo(56, "America/Antigua", "(GMT-04:00) Antigua", "AG", "AST", null),
            new SystemTimezoneOptionInfo(57, "America/Araguaina", "(GMT-03:00) Araguaina", "BR", "BRT", "BRST"),
            new SystemTimezoneOptionInfo(58, "America/Argentina/Buenos_Aires", "(GMT-03:00) Buenos Aires", "AR", "ART",
                "ARST"),
            new SystemTimezoneOptionInfo(59, "America/Argentina/La_Rioja", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(60, "America/Argentina/Rio_Gallegos", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(61, "America/Argentina/Salta", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(62, "America/Argentina/San_Juan", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(63, "America/Argentina/San_Luis", null, null, "ART", "WARST"),
            new SystemTimezoneOptionInfo(64, "America/Argentina/Tucuman", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(65, "America/Argentina/Ushuaia", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(66, "America/Aruba", "(GMT-04:00) Aruba", "AW", "AST", null),
            new SystemTimezoneOptionInfo(67, "America/Asuncion", "(GMT-04:00) Asuncion", "PY", "PYT", "PYST"),
            new SystemTimezoneOptionInfo(68, "America/Bahia", "(GMT-03:00) Salvador", "BR", "BRT", "BRST"),
            new SystemTimezoneOptionInfo(69, "America/Bahia_Banderas", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(70, "America/Barbados", "(GMT-04:00) Barbados", "BB", "AST", "ADT"),
            new SystemTimezoneOptionInfo(71, "America/Belem", "(GMT-03:00) Belem", "BR", "BRT", "BRST"),
            new SystemTimezoneOptionInfo(72, "America/Belize", "(GMT-06:00) Belize", "BZ", "CST", "CDT"),
            new SystemTimezoneOptionInfo(73, "America/Blanc-Sablon", null, null, "AST", "APT"),
            new SystemTimezoneOptionInfo(74, "America/Boa_Vista", "(GMT-04:00) Boa Vista", "BR", "AMT", "AMST"),
            new SystemTimezoneOptionInfo(75, "America/Bogota", "(GMT-05:00) Bogota", "CO", "COT", "COST"),
            new SystemTimezoneOptionInfo(76, "America/Boise", null, null, "MST", "MDT"),
            new SystemTimezoneOptionInfo(77, "America/Buenos_Aires", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(78, "America/Cambridge_Bay", null, null, "MST", "MDT"),
            new SystemTimezoneOptionInfo(79, "America/Campo_Grande", "(GMT-04:00) Campo Grande", "BR", "AMT", "AMST"),
            new SystemTimezoneOptionInfo(80, "America/Cancun", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(81, "America/Caracas", "(GMT-04:30) Caracas", "VE", "VET", null),
            new SystemTimezoneOptionInfo(82, "America/Catamarca", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(83, "America/Cayenne", "(GMT-03:00) Cayenne", "GF", "GFT", null),
            new SystemTimezoneOptionInfo(84, "America/Cayman", "(GMT-05:00) Cayman", "KY", "EST", null),
            new SystemTimezoneOptionInfo(85, "America/Chicago", "(GMT-06:00) Central Time", "US", "CST", "CDT"),
            new SystemTimezoneOptionInfo(86, "America/Chihuahua", null, null, "MST", "MDT"),
            new SystemTimezoneOptionInfo(87, "America/Coral_Harbour", null, null, "EST", "CPT"),
            new SystemTimezoneOptionInfo(88, "America/Cordoba", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(89, "America/Costa_Rica", "(GMT-06:00) Costa Rica", "CR", "CST", "CDT"),
            new SystemTimezoneOptionInfo(90, "America/Creston", null, null, "MST", null),
            new SystemTimezoneOptionInfo(91, "America/Cuiaba", "(GMT-04:00) Cuiaba", "BR", "AMT", "AMST"),
            new SystemTimezoneOptionInfo(92, "America/Curacao", "(GMT-04:00) Curacao", "AN", "AST", null),
            new SystemTimezoneOptionInfo(93, "America/Danmarkshavn", "(GMT+00:00) Danmarkshavn", "GL", "GMT", "WGST"),
            new SystemTimezoneOptionInfo(94, "America/Dawson", null, null, "PST", "PDT"),
            new SystemTimezoneOptionInfo(95, "America/Dawson_Creek", "(GMT-07:00) Mountain Time - Dawson Creek", "CA",
                "MST", "PDT"),
            new SystemTimezoneOptionInfo(96, "America/Denver", "(GMT-07:00) Mountain Time", "US", "MST", "MDT"),
            new SystemTimezoneOptionInfo(97, "America/Detroit", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(98, "America/Dominica", "(GMT-04:00) Dominica", "DM", "AST", null),
            new SystemTimezoneOptionInfo(99, "America/Edmonton", "(GMT-07:00) Mountain Time - Edmonton", "CA", "MST",
                "MDT"),
            new SystemTimezoneOptionInfo(100, "America/Eirunepe", null, null, "ACT", "ACST"),
            new SystemTimezoneOptionInfo(101, "America/El_Salvador", "(GMT-06:00) El Salvador", "SV", "CST", "CDT"),
            new SystemTimezoneOptionInfo(102, "America/Fortaleza", "(GMT-03:00) Fortaleza", "BR", "BRT", "BRST"),
            new SystemTimezoneOptionInfo(103, "America/Glace_Bay", null, null, "AST", "ADT"),
            new SystemTimezoneOptionInfo(104, "America/Godthab", "(GMT-03:00) Godthab", "GL", "WGT", "WGST"),
            new SystemTimezoneOptionInfo(105, "America/Goose_Bay", null, null, "AST", "ADT"),
            new SystemTimezoneOptionInfo(106, "America/Grand_Turk", "(GMT-05:00) Grand Turk", "TC", "EST", "EDT"),
            new SystemTimezoneOptionInfo(107, "America/Grenada", "(GMT-04:00) Grenada", "GD", "AST", null),
            new SystemTimezoneOptionInfo(108, "America/Guadeloupe", "(GMT-04:00) Guadeloupe", "GP", "AST", null),
            new SystemTimezoneOptionInfo(109, "America/Guatemala", "(GMT-06:00) Guatemala", "GT", "CST", "CDT"),
            new SystemTimezoneOptionInfo(110, "America/Guayaquil", "(GMT-05:00) Guayaquil", "EC", "ECT", null),
            new SystemTimezoneOptionInfo(111, "America/Guyana", "(GMT-04:00) Guyana", "GY", "GYT", null),
            new SystemTimezoneOptionInfo(112, "America/Halifax", "(GMT-04:00) Atlantic Time - Halifax", "CA", "AST",
                "ADT"),
            new SystemTimezoneOptionInfo(113, "America/Havana", "(GMT-05:00) Havana", "CU", "CST", "CDT"),
            new SystemTimezoneOptionInfo(114, "America/Hermosillo", "(GMT-07:00) Mountain Time - Hermosillo", "MX",
                "MST", "MDT"),
            new SystemTimezoneOptionInfo(115, "America/Indiana/Knox", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(116, "America/Indiana/Marengo", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(117, "America/Indiana/Petersburg", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(118, "America/Indiana/Tell_City", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(119, "America/Indiana/Vevay", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(120, "America/Indiana/Vincennes", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(121, "America/Indiana/Winamac", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(122, "America/Indianapolis", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(123, "America/Inuvik", null, null, "MST", "MDT"),
            new SystemTimezoneOptionInfo(124, "America/Iqaluit", "(GMT-05:00) Eastern Time - Iqaluit", "CA", "EST",
                "EDT"),
            new SystemTimezoneOptionInfo(125, "America/Jamaica", "(GMT-05:00) Jamaica", "JM", "EST", "EDT"),
            new SystemTimezoneOptionInfo(126, "America/Jujuy", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(127, "America/Juneau", null, null, "AKST", "AKDT"),
            new SystemTimezoneOptionInfo(128, "America/Kentucky/Monticello", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(129, "America/Kralendijk", null, null, "AST", null),
            new SystemTimezoneOptionInfo(130, "America/La_Paz", "(GMT-04:00) La Paz", "BO", "BOT", "BOST"),
            new SystemTimezoneOptionInfo(131, "America/Lima", "(GMT-05:00) Lima", "PE", "PET", "PEST"),
            new SystemTimezoneOptionInfo(132, "America/Los_Angeles", "(GMT-08:00) Pacific Time", "US", "PST", "PDT"),
            new SystemTimezoneOptionInfo(133, "America/Louisville", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(134, "America/Lower_Princes", null, null, "AST", null),
            new SystemTimezoneOptionInfo(135, "America/Maceio", "(GMT-03:00) Maceio", "BR", "BRT", "BRST"),
            new SystemTimezoneOptionInfo(136, "America/Managua", "(GMT-06:00) Managua", "NI", "CST", "CDT"),
            new SystemTimezoneOptionInfo(137, "America/Manaus", "(GMT-04:00) Manaus", "BR", "AMT", "AMST"),
            new SystemTimezoneOptionInfo(138, "America/Marigot", null, null, "AST", null),
            new SystemTimezoneOptionInfo(139, "America/Martinique", "(GMT-04:00) Martinique", "MQ", "AST", "ADT"),
            new SystemTimezoneOptionInfo(140, "America/Matamoros", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(141, "America/Mazatlan", "(GMT-07:00) Mountain Time - Chihuahua, Mazatlan",
                "MX", "MST", "MDT"),
            new SystemTimezoneOptionInfo(142, "America/Mendoza", null, null, "ART", "ARST"),
            new SystemTimezoneOptionInfo(143, "America/Menominee", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(144, "America/Merida", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(145, "America/Mexico_City", "(GMT-06:00) Central Time - Mexico City", "MX",
                "CST", "CDT"),
            new SystemTimezoneOptionInfo(146, "America/Miquelon", "(GMT-03:00) Miquelon", "PM", "PMST", "PMDT"),
            new SystemTimezoneOptionInfo(147, "America/Moncton", null, null, "AST", "ADT"),
            new SystemTimezoneOptionInfo(148, "America/Monterrey", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(149, "America/Montevideo", "(GMT-03:00) Montevideo", "UY", "UYT", "UYST"),
            new SystemTimezoneOptionInfo(150, "America/Montreal", "(GMT-05:00) Eastern Time - Montreal", "CA", "EST",
                "EDT"),
            new SystemTimezoneOptionInfo(151, "America/Montserrat", "(GMT-04:00) Montserrat", "MS", "AST", null),
            new SystemTimezoneOptionInfo(152, "America/Nassau", "(GMT-05:00) Nassau", "BS", "EST", "EDT"),
            new SystemTimezoneOptionInfo(153, "America/New_York", "(GMT-05:00) Eastern Time", "US", "EST", "EDT"),
            new SystemTimezoneOptionInfo(154, "America/Nipigon", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(155, "America/Nome", null, null, "AKST", "AKDT"),
            new SystemTimezoneOptionInfo(156, "America/Noronha", "(GMT-02:00) Noronha", "BR", "FNT", "FNST"),
            new SystemTimezoneOptionInfo(157, "America/North_Dakota/Beulah", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(158, "America/North_Dakota/Center", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(159, "America/North_Dakota/New_Salem", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(160, "America/Ojinaga", null, null, "MST", "MDT"),
            new SystemTimezoneOptionInfo(161, "America/Panama", "(GMT-05:00) Panama", "PA", "EST", null),
            new SystemTimezoneOptionInfo(162, "America/Pangnirtung", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(163, "America/Paramaribo", "(GMT-03:00) Paramaribo", "SR", "SRT", null),
            new SystemTimezoneOptionInfo(164, "America/Phoenix", "(GMT-07:00) Mountain Time - Arizona", "US", "MST",
                "MDT"),
            new SystemTimezoneOptionInfo(165, "America/Port_of_Spain", "(GMT-04:00) Port of Spain", "TT", "AST", null),
            new SystemTimezoneOptionInfo(166, "America/Port-au-Prince", "(GMT-05:00) Port-au-Prince", "HT", "EST",
                "EDT"),
            new SystemTimezoneOptionInfo(167, "America/Porto_Velho", "(GMT-04:00) Porto Velho", "BR", "AMT", "AMST"),
            new SystemTimezoneOptionInfo(168, "America/Puerto_Rico", "(GMT-04:00) Puerto Rico", "PR", "AST", "APT"),
            new SystemTimezoneOptionInfo(169, "America/Rainy_River", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(170, "America/Rankin_Inlet", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(171, "America/Recife", "(GMT-03:00) Recife", "BR", "BRT", "BRST"),
            new SystemTimezoneOptionInfo(172, "America/Regina", "(GMT-06:00) Central Time - Regina", "CA", "CST",
                "MDT"),
            new SystemTimezoneOptionInfo(173, "America/Resolute", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(174, "America/Rio_Branco", "(GMT-04:00) Rio Branco", "BR", "ACT", "ACST"),
            new SystemTimezoneOptionInfo(175, "America/Santa_Isabel", null, null, "PST", "PDT"),
            new SystemTimezoneOptionInfo(176, "America/Santarem", null, null, "BRT", "AMST"),
            new SystemTimezoneOptionInfo(177, "America/Santiago", "(GMT-04:00) Santiago", "CL", "CLT", "CLST"),
            new SystemTimezoneOptionInfo(178, "America/Santo_Domingo", "(GMT-04:00) Santo Domingo", "DO", "AST",
                "EHDT"),
            new SystemTimezoneOptionInfo(179, "America/Sao_Paulo", "(GMT-03:00) Sao Paulo", "BR", "BRT", "BRST"),
            new SystemTimezoneOptionInfo(180, "America/Scoresbysund", "(GMT-01:00) Scoresbysund", "GL", "EGT", "EGST"),
            new SystemTimezoneOptionInfo(181, "America/Shiprock", null, null, null, null),
            new SystemTimezoneOptionInfo(182, "America/Sitka", null, null, "AKST", "AKDT"),
            new SystemTimezoneOptionInfo(183, "America/St_Barthelemy", null, null, "AST", null),
            new SystemTimezoneOptionInfo(184, "America/St_Johns", "(GMT-03:30) Newfoundland Time - St. Johns", "CA",
                "NST", "NDT"),
            new SystemTimezoneOptionInfo(185, "America/St_Kitts", "(GMT-04:00) St. Kitts", "KN", "AST", null),
            new SystemTimezoneOptionInfo(186, "America/St_Lucia", "(GMT-04:00) St. Lucia", "LC", "AST", null),
            new SystemTimezoneOptionInfo(187, "America/St_Thomas", "(GMT-04:00) St. Thomas", "VI", "AST", null),
            new SystemTimezoneOptionInfo(188, "America/St_Vincent", "(GMT-04:00) St. Vincent", "VC", "AST", null),
            new SystemTimezoneOptionInfo(189, "America/Swift_Current", null, null, "CST", "MDT"),
            new SystemTimezoneOptionInfo(190, "America/Tegucigalpa", "(GMT-06:00) Central Time - Tegucigalpa", "HN",
                "CST", "CDT"),
            new SystemTimezoneOptionInfo(191, "America/Thule", "(GMT-04:00) Thule", "GL", "AST", "ADT"),
            new SystemTimezoneOptionInfo(192, "America/Thunder_Bay", null, null, "EST", "EDT"),
            new SystemTimezoneOptionInfo(193, "America/Tijuana", "(GMT-08:00) Pacific Time - Tijuana", "MX", "PST",
                "PDT"),
            new SystemTimezoneOptionInfo(194, "America/Toronto", "(GMT-05:00) Eastern Time - Toronto", "CA", "EST",
                "EDT"),
            new SystemTimezoneOptionInfo(195, "America/Tortola", "(GMT-04:00) Tortola", "VG", "AST", null),
            new SystemTimezoneOptionInfo(196, "America/Vancouver", "(GMT-08:00) Pacific Time - Vancouver", "CA", "PST",
                "PDT"),
            new SystemTimezoneOptionInfo(197, "America/Whitehorse", "(GMT-08:00) Pacific Time - Whitehorse", "CA",
                "PST", "PDT"),
            new SystemTimezoneOptionInfo(198, "America/Winnipeg", "(GMT-06:00) Central Time - Winnipeg", "CA", "CST",
                "CDT"),
            new SystemTimezoneOptionInfo(199, "America/Yakutat", null, null, "AKST", "AKDT"),
            new SystemTimezoneOptionInfo(200, "America/Yellowknife", "(GMT-07:00) Mountain Time - Yellowknife", "CA",
                "MST", "MDT"),
            new SystemTimezoneOptionInfo(201, "Antarctica/Casey", "(GMT+08:00) Casey", "AQ", "WST", null),
            new SystemTimezoneOptionInfo(202, "Antarctica/Davis", "(GMT+07:00) Davis", "AQ", "DAVT", null),
            new SystemTimezoneOptionInfo(203, "Antarctica/DumontDUrville", "(GMT+10:00) Dumont D'Urville", "AQ", "DDUT",
                null),
            new SystemTimezoneOptionInfo(204, "Antarctica/Macquarie", null, null, "MIST", "EST"),
            new SystemTimezoneOptionInfo(205, "Antarctica/Mawson", "(GMT+05:00) Mawson", "AQ", "MAWT", null),
            new SystemTimezoneOptionInfo(206, "Antarctica/McMurdo", null, null, "NZST", "NZDT"),
            new SystemTimezoneOptionInfo(207, "Antarctica/Palmer", "(GMT-04:00) Palmer", "AQ", "CLT", "CLST"),
            new SystemTimezoneOptionInfo(208, "Antarctica/Rothera", "(GMT-03:00) Rothera", "AQ", "ROTT", null),
            new SystemTimezoneOptionInfo(209, "Antarctica/South_Pole", null, null, null, null),
            new SystemTimezoneOptionInfo(210, "Antarctica/Syowa", "(GMT+03:00) Syowa", "AQ", "SYOT", null),
            new SystemTimezoneOptionInfo(211, "Antarctica/Vostok", "(GMT+06:00) Vostok", "AQ", "VOST", null),
            new SystemTimezoneOptionInfo(212, "Arctic/Longyearbyen", null, null, null, null),
            new SystemTimezoneOptionInfo(213, "Asia/Aden", "(GMT+03:00) Aden", "YE", "AST", null),
            new SystemTimezoneOptionInfo(214, "Asia/Almaty", "(GMT+06:00) Almaty", "KZ", "ALMT", "ALMST"),
            new SystemTimezoneOptionInfo(215, "Asia/Amman", "(GMT+02:00) Amman", "JO", "EET", "EEST"),
            new SystemTimezoneOptionInfo(216, "Asia/Anadyr", null, null, "ANAT", "ANAST"),
            new SystemTimezoneOptionInfo(217, "Asia/Aqtau", "(GMT+05:00) Aqtau", "KZ", "AQTT", "AQTST"),
            new SystemTimezoneOptionInfo(218, "Asia/Aqtobe", "(GMT+05:00) Aqtobe", "KZ", "AQTT", "AQTST"),
            new SystemTimezoneOptionInfo(219, "Asia/Ashgabat", "(GMT+05:00) Ashgabat", "TM", "TMT", "ASHST"),
            new SystemTimezoneOptionInfo(220, "Asia/Baghdad", "(GMT+03:00) Baghdad", "IQ", "AST", "ADT"),
            new SystemTimezoneOptionInfo(221, "Asia/Bahrain", "(GMT+03:00) Bahrain", "BH", "AST", null),
            new SystemTimezoneOptionInfo(222, "Asia/Baku", "(GMT+04:00) Baku", "AZ", "AZT", "AZST"),
            new SystemTimezoneOptionInfo(223, "Asia/Bangkok", "(GMT+07:00) Bangkok", "TH", "ICT", null),
            new SystemTimezoneOptionInfo(224, "Asia/Beirut", "(GMT+02:00) Beirut", "LB", "EET", "EEST"),
            new SystemTimezoneOptionInfo(225, "Asia/Bishkek", "(GMT+06:00) Bishkek", "KG", "KGT", "KGST"),
            new SystemTimezoneOptionInfo(226, "Asia/Brunei", "(GMT+08:00) Brunei", "BN", "BNT", null),
            new SystemTimezoneOptionInfo(227, "Asia/Calcutta", "(GMT+05:30) India Standard Time", "IN", "IST", "IST"),
            new SystemTimezoneOptionInfo(228, "Asia/Choibalsan", "(GMT+08:00) Choibalsan", "MN", "CHOT", "CHOST"),
            new SystemTimezoneOptionInfo(229, "Asia/Chongqing", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(230, "Asia/Colombo", "(GMT+05:30) Colombo", "LK", "IST", "IST"),
            new SystemTimezoneOptionInfo(231, "Asia/Damascus", "(GMT+02:00) Damascus", "SY", "EET", "EEST"),
            new SystemTimezoneOptionInfo(232, "Asia/Dhaka", "(GMT+06:00) Dhaka", "BD", "BDT", "BDST"),
            new SystemTimezoneOptionInfo(233, "Asia/Dili", "(GMT+09:00) Dili", "TL", "TLT", null),
            new SystemTimezoneOptionInfo(234, "Asia/Dubai", "(GMT+04:00) Dubai", "AE", "GST", null),
            new SystemTimezoneOptionInfo(235, "Asia/Dushanbe", "(GMT+05:00) Dushanbe", "TJ", "TJT", "DUSST"),
            new SystemTimezoneOptionInfo(236, "Asia/Gaza", "(GMT+02:00) Gaza", "PS", "EET", "EEST"),
            new SystemTimezoneOptionInfo(237, "Asia/Harbin", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(238, "Asia/Hebron", null, null, "EET", "EEST"),
            new SystemTimezoneOptionInfo(239, "Asia/Hong_Kong", "(GMT+08:00) Hong Kong", "HK", "HKT", "HKST"),
            new SystemTimezoneOptionInfo(240, "Asia/Hovd", "(GMT+07:00) Hovd", "MN", "HOVT", "HOVST"),
            new SystemTimezoneOptionInfo(241, "Asia/Irkutsk", "(GMT+09:00) Moscow+05 - Irkutsk", "RU", "IRKT", "IRKST"),
            new SystemTimezoneOptionInfo(242, "Asia/Jakarta", "(GMT+07:00) Jakarta", "ID", "WIB", null),
            new SystemTimezoneOptionInfo(243, "Asia/Jayapura", "(GMT+09:00) Jayapura", "ID", "WIT", null),
            new SystemTimezoneOptionInfo(244, "Asia/Jerusalem", "(GMT+02:00) Jerusalem", "IL", "IST", "IDT"),
            new SystemTimezoneOptionInfo(245, "Asia/Kabul", "(GMT+04:30) Kabul", "AF", "AFT", null),
            new SystemTimezoneOptionInfo(246, "Asia/Kamchatka", "(GMT+12:00) Moscow+08 - Petropavlovsk-Kamchatskiy",
                "RU", "PETT", "PETST"),
            new SystemTimezoneOptionInfo(247, "Asia/Karachi", "(GMT+05:00) Karachi", "PK", "PKT", "PKST"),
            new SystemTimezoneOptionInfo(248, "Asia/Kashgar", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(249, "Asia/Katmandu", "(GMT+05:45) Katmandu", "NP", "NPT", null),
            new SystemTimezoneOptionInfo(250, "Asia/Krasnoyarsk", "(GMT+08:00) Moscow+04 - Krasnoyarsk", "RU", "KRAT",
                "KRAST"),
            new SystemTimezoneOptionInfo(251, "Asia/Kuala_Lumpur", "(GMT+08:00) Kuala Lumpur", "MY", "MYT", "MALST"),
            new SystemTimezoneOptionInfo(252, "Asia/Kuching", null, null, "MYT", "BORTST"),
            new SystemTimezoneOptionInfo(253, "Asia/Kuwait", "(GMT+03:00) Kuwait", "KW", "AST", null),
            new SystemTimezoneOptionInfo(254, "Asia/Macau", "(GMT+08:00) Macau", "MO", "CST", "MOST"),
            new SystemTimezoneOptionInfo(255, "Asia/Magadan", "(GMT+12:00) Moscow+08 - Magadan", "RU", "MAGT", "MAGST"),
            new SystemTimezoneOptionInfo(256, "Asia/Makassar", "(GMT+08:00) Makassar", "ID", "WITA", null),
            new SystemTimezoneOptionInfo(257, "Asia/Manila", "(GMT+08:00) Manila", "PH", "PHT", "PHST"),
            new SystemTimezoneOptionInfo(258, "Asia/Muscat", "(GMT+04:00) Muscat", "OM", "GST", null),
            new SystemTimezoneOptionInfo(259, "Asia/Nicosia", "(GMT+02:00) Nicosia", "CY", "EET", "EEST"),
            new SystemTimezoneOptionInfo(260, "Asia/Novokuznetsk", null, null, "NOVT", "NOVST"),
            new SystemTimezoneOptionInfo(261, "Asia/Novosibirsk", null, null, "NOVT", "NOVST"),
            new SystemTimezoneOptionInfo(262, "Asia/Omsk", "(GMT+07:00) Moscow+03 - Omsk, Novosibirsk", "RU", "OMST",
                "OMSST"),
            new SystemTimezoneOptionInfo(263, "Asia/Oral", null, null, "ORAT", "ORAST"),
            new SystemTimezoneOptionInfo(264, "Asia/Phnom_Penh", "(GMT+07:00) Phnom Penh", "KH", "ICT", null),
            new SystemTimezoneOptionInfo(265, "Asia/Pontianak", null, null, "WIB", null),
            new SystemTimezoneOptionInfo(266, "Asia/Pyongyang", "(GMT+09:00) Pyongyang", "KP", "KST", null),
            new SystemTimezoneOptionInfo(267, "Asia/Qatar", "(GMT+03:00) Qatar", "QA", "AST", null),
            new SystemTimezoneOptionInfo(268, "Asia/Qyzylorda", null, null, "QYZT", "QYZST"),
            new SystemTimezoneOptionInfo(269, "Asia/Rangoon", "(GMT+06:30) Rangoon", "MM", "MMT", null),
            new SystemTimezoneOptionInfo(270, "Asia/Riyadh", "(GMT+03:00) Riyadh", "SA", "AST", null),
            new SystemTimezoneOptionInfo(271, "Asia/Saigon", "(GMT+07:00) Hanoi", "VN", "ICT", null),
            new SystemTimezoneOptionInfo(272, "Asia/Sakhalin", null, null, "SAKT", "SAKST"),
            new SystemTimezoneOptionInfo(273, "Asia/Samarkand", null, null, "UZT", "UZST"),
            new SystemTimezoneOptionInfo(274, "Asia/Seoul", "(GMT+09:00) Seoul", "KR", "KST", "KDT"),
            new SystemTimezoneOptionInfo(275, "Asia/Shanghai", "(GMT+08:00) China Time - Beijing", "CN", "CST", "CDT"),
            new SystemTimezoneOptionInfo(276, "Asia/Singapore", "(GMT+08:00) Singapore", "SG", "SGT", "MALST"),
            new SystemTimezoneOptionInfo(277, "Asia/Taipei", "(GMT+08:00) Taipei", "TW", "CST", "CDT"),
            new SystemTimezoneOptionInfo(278, "Asia/Tashkent", "(GMT+05:00) Tashkent", "UZ", "UZT", "UZST"),
            new SystemTimezoneOptionInfo(279, "Asia/Tbilisi", "(GMT+04:00) Tbilisi", "GE", "GET", "GEST"),
            new SystemTimezoneOptionInfo(280, "Asia/Tehran", "(GMT+03:30) Tehran", "IR", "IRST", "IRDT"),
            new SystemTimezoneOptionInfo(281, "Asia/Thimphu", "(GMT+06:00) Thimphu", "BT", "BTT", null),
            new SystemTimezoneOptionInfo(282, "Asia/Tokyo", "(GMT+09:00) Tokyo", "JP", "JST", "JDT"),
            new SystemTimezoneOptionInfo(283, "Asia/Ulaanbaatar", "(GMT+08:00) Ulaanbaatar", "MN", "ULAT", "ULAST"),
            new SystemTimezoneOptionInfo(284, "Asia/Urumqi", null, null, "CST", "CDT"),
            new SystemTimezoneOptionInfo(285, "Asia/Vientiane", "(GMT+07:00) Vientiane", "LA", "ICT", null),
            new SystemTimezoneOptionInfo(286, "Asia/Vladivostok", "(GMT+11:00) Moscow+07 - Yuzhno-Sakhalinsk", "RU",
                "VLAT", "VLAST"),
            new SystemTimezoneOptionInfo(287, "Asia/Yakutsk", "(GMT+10:00) Moscow+06 - Yakutsk", "RU", "YAKT", "YAKST"),
            new SystemTimezoneOptionInfo(288, "Asia/Yekaterinburg", "(GMT+06:00) Moscow+02 - Yekaterinburg", "RU",
                "YEKT", "YEKST"),
            new SystemTimezoneOptionInfo(289, "Asia/Yerevan", "(GMT+04:00) Yerevan", "AM", "AMT", "AMST"),
            new SystemTimezoneOptionInfo(290, "Atlantic/Azores", "(GMT-01:00) Azores", "PT", "AZOT", "AZOST"),
            new SystemTimezoneOptionInfo(291, "Atlantic/Bermuda", "(GMT-04:00) Bermuda", "BM", "AST", "ADT"),
            new SystemTimezoneOptionInfo(292, "Atlantic/Canary", "(GMT+00:00) Canary Islands", "ES", "WET", "WEST"),
            new SystemTimezoneOptionInfo(293, "Atlantic/Cape_Verde", "(GMT-01:00) Cape Verde", "CV", "CVT", "CVST"),
            new SystemTimezoneOptionInfo(294, "Atlantic/Faeroe", null, null, "WET", "WEST"),
            new SystemTimezoneOptionInfo(295, "Atlantic/Faroe", "(GMT+00:00) Faeroe", "FO", "WET", "WEST"),
            new SystemTimezoneOptionInfo(296, "Atlantic/Madeira", null, null, "WET", "WEST"),
            new SystemTimezoneOptionInfo(297, "Atlantic/Reykjavik", "(GMT+00:00) Reykjavik", "IS", "GMT", "ISST"),
            new SystemTimezoneOptionInfo(298, "Atlantic/South_Georgia", "(GMT-02:00) South Georgia", "GS", "GST", null),
            new SystemTimezoneOptionInfo(299, "Atlantic/St_Helena", "(GMT+00:00) St Helena", "SH", "GMT", null),
            new SystemTimezoneOptionInfo(300, "Atlantic/Stanley", "(GMT-03:00) Stanley", "FK", "FKST", "FKST"),
            new SystemTimezoneOptionInfo(301, "Australia/Adelaide", "(GMT+09:30) Central Time - Adelaide", "AU", "CST",
                "CST"),
            new SystemTimezoneOptionInfo(302, "Australia/Brisbane", "(GMT+10:00) Eastern Time - Brisbane", "AU", "EST",
                "EST"),
            new SystemTimezoneOptionInfo(303, "Australia/Broken_Hill", null, null, "CST", "CST"),
            new SystemTimezoneOptionInfo(304, "Australia/Currie", null, null, "EST", "EST"),
            new SystemTimezoneOptionInfo(305, "Australia/Darwin", "(GMT+09:30) Central Time - Darwin", "AU", "CST",
                "CST"),
            new SystemTimezoneOptionInfo(306, "Australia/Hobart", "(GMT+10:00) Eastern Time - Hobart", "AU", "EST",
                "EST"),
            new SystemTimezoneOptionInfo(307, "Australia/Lindeman", null, null, "EST", "EST"),
            new SystemTimezoneOptionInfo(308, "Australia/Melbourne", null, null, "EST", "EST"),
            new SystemTimezoneOptionInfo(309, "Australia/Perth", "(GMT+08:00) Western Time - Perth", "AU", "WST",
                "WST"),
            new SystemTimezoneOptionInfo(310, "Australia/Sydney", "(GMT+10:00) Eastern Time - Melbourne, Sydney", "AU",
                "EST", "EST"),
            new SystemTimezoneOptionInfo(311, "CST6CDT", null, null, null, null),
            new SystemTimezoneOptionInfo(312, "EST5EDT", null, null, null, null),
            new SystemTimezoneOptionInfo(313, "Etc/GMT", "(GMT+00:00) GMT (no daylight saving)", "ZZ", "GMT", null),
            new SystemTimezoneOptionInfo(314, "Etc/GMT+1", null, null, "GMT+1", null),
            new SystemTimezoneOptionInfo(315, "Etc/GMT+10", null, null, "GMT+10", null),
            new SystemTimezoneOptionInfo(316, "Etc/GMT+11", null, null, "GMT+11", null),
            new SystemTimezoneOptionInfo(317, "Etc/GMT+12", null, null, "GMT+12", null),
            new SystemTimezoneOptionInfo(318, "Etc/GMT+2", null, null, "GMT+2", null),
            new SystemTimezoneOptionInfo(319, "Etc/GMT+3", null, null, "GMT+3", null),
            new SystemTimezoneOptionInfo(320, "Etc/GMT+4", null, null, "GMT+4", null),
            new SystemTimezoneOptionInfo(321, "Etc/GMT+5", null, null, "GMT+5", null),
            new SystemTimezoneOptionInfo(322, "Etc/GMT+6", null, null, "GMT+6", null),
            new SystemTimezoneOptionInfo(323, "Etc/GMT+7", null, null, "GMT+7", null),
            new SystemTimezoneOptionInfo(324, "Etc/GMT-1", null, null, "GMT-1", null),
            new SystemTimezoneOptionInfo(325, "Etc/GMT-10", null, null, "GMT-10", null),
            new SystemTimezoneOptionInfo(326, "Etc/GMT-11", null, null, "GMT-11", null),
            new SystemTimezoneOptionInfo(327, "Etc/GMT-12", null, null, "GMT-12", null),
            new SystemTimezoneOptionInfo(328, "Etc/GMT-13", null, null, "GMT-13", null),
            new SystemTimezoneOptionInfo(329, "Etc/GMT-2", null, null, "GMT-2", null),
            new SystemTimezoneOptionInfo(330, "Etc/GMT-3", null, null, "GMT-3", null),
            new SystemTimezoneOptionInfo(331, "Etc/GMT-4", null, null, "GMT-4", null),
            new SystemTimezoneOptionInfo(332, "Etc/GMT-5", null, null, "GMT-5", null),
            new SystemTimezoneOptionInfo(333, "Etc/GMT-6", null, null, "GMT-6", null),
            new SystemTimezoneOptionInfo(334, "Etc/GMT-7", null, null, "GMT-7", null),
            new SystemTimezoneOptionInfo(335, "Etc/GMT-8", null, null, "GMT-8", null),
            new SystemTimezoneOptionInfo(336, "Etc/GMT-9", null, null, "GMT-9", null),
            new SystemTimezoneOptionInfo(337, "Europe/Amsterdam", "(GMT+01:00) Amsterdam", "NL", "CET", "CEST"),
            new SystemTimezoneOptionInfo(338, "Europe/Andorra", "(GMT+01:00) Andorra", "AD", "CET", "CEST"),
            new SystemTimezoneOptionInfo(339, "Europe/Athens", "(GMT+02:00) Athens", "GR", "EET", "EEST"),
            new SystemTimezoneOptionInfo(340, "Europe/Belgrade", "(GMT+01:00) Central European Time - Belgrade", "SI",
                "CET", "CEST"),
            new SystemTimezoneOptionInfo(341, "Europe/Berlin", "(GMT+01:00) Berlin", "DE", "CET", "CEST"),
            new SystemTimezoneOptionInfo(342, "Europe/Bratislava", null, null, "CET", "CEST"),
            new SystemTimezoneOptionInfo(343, "Europe/Brussels", "(GMT+01:00) Brussels", "BE", "CET", "CEST"),
            new SystemTimezoneOptionInfo(344, "Europe/Bucharest", "(GMT+02:00) Bucharest", "RO", "EET", "EEST"),
            new SystemTimezoneOptionInfo(345, "Europe/Budapest", "(GMT+01:00) Budapest", "HU", "CET", "CEST"),
            new SystemTimezoneOptionInfo(346, "Europe/Chisinau", "(GMT+02:00) Chisinau", "MD", "EET", "EEST"),
            new SystemTimezoneOptionInfo(347, "Europe/Copenhagen", "(GMT+01:00) Copenhagen", "DK", "CET", "CEST"),
            new SystemTimezoneOptionInfo(348, "Europe/Dublin", "(GMT+00:00) Dublin", "IE", "GMT", "IST"),
            new SystemTimezoneOptionInfo(349, "Europe/Gibraltar", "(GMT+01:00) Gibraltar", "GI", "CET", "CEST"),
            new SystemTimezoneOptionInfo(350, "Europe/Guernsey", null, null, "GMT", "BST"),
            new SystemTimezoneOptionInfo(351, "Europe/Helsinki", "(GMT+02:00) Helsinki", "FI", "EET", "EEST"),
            new SystemTimezoneOptionInfo(352, "Europe/Isle_of_Man", null, null, "GMT", "BST"),
            new SystemTimezoneOptionInfo(353, "Europe/Istanbul", "(GMT+02:00) Istanbul", "TR", "EET", "EEST"),
            new SystemTimezoneOptionInfo(354, "Europe/Jersey", null, null, "GMT", "BST"),
            new SystemTimezoneOptionInfo(355, "Europe/Kaliningrad", "(GMT+03:00) Moscow-01 - Kaliningrad", "RU", "FET",
                "EEST"),
            new SystemTimezoneOptionInfo(356, "Europe/Kiev", "(GMT+02:00) Kiev", "UA", "EET", "EEST"),
            new SystemTimezoneOptionInfo(357, "Europe/Lisbon", "(GMT+00:00) Lisbon", "PT", "WET", "WEST"),
            new SystemTimezoneOptionInfo(358, "Europe/Ljubljana", null, null, "CET", "CEST"),
            new SystemTimezoneOptionInfo(359, "Europe/London", "(GMT+00:00) London", "GB", "GMT", "BST"),
            new SystemTimezoneOptionInfo(360, "Europe/Luxembourg", "(GMT+01:00) Luxembourg", "LU", "CET", "CEST"),
            new SystemTimezoneOptionInfo(361, "Europe/Madrid", "(GMT+01:00) Madrid", "ES", "CET", "CEST"),
            new SystemTimezoneOptionInfo(362, "Europe/Malta", "(GMT+01:00) Malta", "MT", "CET", "CEST"),
            new SystemTimezoneOptionInfo(363, "Europe/Mariehamn", null, null, "EET", "EEST"),
            new SystemTimezoneOptionInfo(364, "Europe/Minsk", "(GMT+03:00) Minsk", "BY", "FET", "EEST"),
            new SystemTimezoneOptionInfo(365, "Europe/Monaco", "(GMT+01:00) Monaco", "MC", "CET", "CEST"),
            new SystemTimezoneOptionInfo(366, "Europe/Moscow", "(GMT+04:00) Moscow+00", "RU", "MSK", "MSD"),
            new SystemTimezoneOptionInfo(367, "Europe/Oslo", "(GMT+01:00) Oslo", "SJ", "CET", "CEST"),
            new SystemTimezoneOptionInfo(368, "Europe/Paris", "(GMT+01:00) Paris", "FR", "CET", "CEST"),
            new SystemTimezoneOptionInfo(369, "Europe/Podgorica", null, null, "CET", "CEST"),
            new SystemTimezoneOptionInfo(370, "Europe/Prague", "(GMT+01:00) Central European Time - Prague", "SK",
                "CET", "CEST"),
            new SystemTimezoneOptionInfo(371, "Europe/Riga", "(GMT+02:00) Riga", "LV", "EET", "EEST"),
            new SystemTimezoneOptionInfo(372, "Europe/Rome", "(GMT+01:00) Rome", "VA", "CET", "CEST"),
            new SystemTimezoneOptionInfo(373, "Europe/Samara", "(GMT+04:00) Moscow+00 - Samara", "RU", "SAMT", "SAMST"),
            new SystemTimezoneOptionInfo(374, "Europe/San_Marino", null, null, "CET", "CEST"),
            new SystemTimezoneOptionInfo(375, "Europe/Sarajevo", null, null, "CET", "CEST"),
            new SystemTimezoneOptionInfo(376, "Europe/Simferopol", null, null, "MSK", "EEST"),
            new SystemTimezoneOptionInfo(377, "Europe/Skopje", null, null, "CET", "CEST"),
            new SystemTimezoneOptionInfo(378, "Europe/Sofia", "(GMT+02:00) Sofia", "BG", "EET", "EEST"),
            new SystemTimezoneOptionInfo(379, "Europe/Stockholm", "(GMT+01:00) Stockholm", "SE", "CET", "CEST"),
            new SystemTimezoneOptionInfo(380, "Europe/Tallinn", "(GMT+02:00) Tallinn", "EE", "EET", "EEST"),
            new SystemTimezoneOptionInfo(381, "Europe/Tirane", "(GMT+01:00) Tirane", "AL", "CET", "CEST"),
            new SystemTimezoneOptionInfo(382, "Europe/Uzhgorod", null, null, "EET", "EEST"),
            new SystemTimezoneOptionInfo(383, "Europe/Vaduz", "(GMT+01:00) Vaduz", "LI", "CET", "CEST"),
            new SystemTimezoneOptionInfo(384, "Europe/Vatican", null, null, "CET", "CEST"),
            new SystemTimezoneOptionInfo(385, "Europe/Vienna", "(GMT+01:00) Vienna", "AT", "CET", "CEST"),
            new SystemTimezoneOptionInfo(386, "Europe/Vilnius", "(GMT+02:00) Vilnius", "LT", "EET", "EEST"),
            new SystemTimezoneOptionInfo(387, "Europe/Volgograd", null, null, "VOLT", "VOLST"),
            new SystemTimezoneOptionInfo(388, "Europe/Warsaw", "(GMT+01:00) Warsaw", "PL", "CET", "CEST"),
            new SystemTimezoneOptionInfo(389, "Europe/Zagreb", null, null, "CET", "CEST"),
            new SystemTimezoneOptionInfo(390, "Europe/Zaporozhye", null, null, "EET", "EEST"),
            new SystemTimezoneOptionInfo(391, "Europe/Zurich", "(GMT+01:00) Zurich", "CH", "CET", "CEST"),
            new SystemTimezoneOptionInfo(392, "Indian/Antananarivo", "(GMT+03:00) Antananarivo", "MG", "EAT", "EAST"),
            new SystemTimezoneOptionInfo(393, "Indian/Chagos", "(GMT+06:00) Chagos", "IO", "IOT", null),
            new SystemTimezoneOptionInfo(394, "Indian/Christmas", "(GMT+07:00) Christmas", "CX", "CXT", null),
            new SystemTimezoneOptionInfo(395, "Indian/Cocos", "(GMT+06:30) Cocos", "CC", "CCT", null),
            new SystemTimezoneOptionInfo(396, "Indian/Comoro", "(GMT+03:00) Comoro", "KM", "EAT", null),
            new SystemTimezoneOptionInfo(397, "Indian/Kerguelen", "(GMT+05:00) Kerguelen", "TF", "TFT", null),
            new SystemTimezoneOptionInfo(398, "Indian/Mahe", "(GMT+04:00) Mahe", "SC", "SCT", null),
            new SystemTimezoneOptionInfo(399, "Indian/Maldives", "(GMT+05:00) Maldives", "MV", "MVT", null),
            new SystemTimezoneOptionInfo(400, "Indian/Mauritius", "(GMT+04:00) Mauritius", "MU", "MUT", "MUST"),
            new SystemTimezoneOptionInfo(401, "Indian/Mayotte", "(GMT+03:00) Mayotte", "YT", "EAT", null),
            new SystemTimezoneOptionInfo(402, "Indian/Reunion", "(GMT+04:00) Reunion", "RE", "RET", null),
            new SystemTimezoneOptionInfo(403, "MST7MDT", null, null, null, null),
            new SystemTimezoneOptionInfo(404, "Pacific/Apia", "(GMT+13:00) Apia", "WS", "WST", "WSDT"),
            new SystemTimezoneOptionInfo(405, "Pacific/Auckland", "(GMT+12:00) Auckland", "NZ", "NZST", "NZDT"),
            new SystemTimezoneOptionInfo(406, "Pacific/Easter", "(GMT-06:00) Easter Island", "CL", "EAST", "EASST"),
            new SystemTimezoneOptionInfo(407, "Pacific/Efate", "(GMT+11:00) Efate", "VU", "VUT", "VUST"),
            new SystemTimezoneOptionInfo(408, "Pacific/Enderbury", "(GMT+13:00) Enderbury", "UM", "PHOT", null),
            new SystemTimezoneOptionInfo(409, "Pacific/Fakaofo", "(GMT+13:00) Fakaofo", "TK", "TKT", null),
            new SystemTimezoneOptionInfo(410, "Pacific/Fiji", "(GMT+12:00) Fiji", "FJ", "FJT", "FJST"),
            new SystemTimezoneOptionInfo(411, "Pacific/Funafuti", "(GMT+12:00) Funafuti", "TV", "TVT", null),
            new SystemTimezoneOptionInfo(412, "Pacific/Galapagos", "(GMT-06:00) Galapagos", "EC", "GALT", null),
            new SystemTimezoneOptionInfo(413, "Pacific/Gambier", "(GMT-09:00) Gambier", "PF", "GAMT", null),
            new SystemTimezoneOptionInfo(414, "Pacific/Guadalcanal", "(GMT+11:00) Guadalcanal", "SB", "SBT", null),
            new SystemTimezoneOptionInfo(415, "Pacific/Guam", "(GMT+10:00) Guam", "GU", "ChST", null),
            new SystemTimezoneOptionInfo(416, "Pacific/Honolulu", "(GMT-10:00) Hawaii Time", "US", "HST", "HDT"),
            new SystemTimezoneOptionInfo(417, "Pacific/Johnston", "(GMT-10:00) Johnston", "UM", "HST", "HDT"),
            new SystemTimezoneOptionInfo(418, "Pacific/Kiritimati", "(GMT+14:00) Kiritimati", "KI", "LINT", null),
            new SystemTimezoneOptionInfo(419, "Pacific/Kosrae", "(GMT+11:00) Kosrae", "FM", "KOST", null),
            new SystemTimezoneOptionInfo(420, "Pacific/Kwajalein", "(GMT+12:00) Kwajalein", "MH", "MHT", null),
            new SystemTimezoneOptionInfo(421, "Pacific/Majuro", "(GMT+12:00) Majuro", "MH", "MHT", null),
            new SystemTimezoneOptionInfo(422, "Pacific/Marquesas", "(GMT-09:30) Marquesas", "PF", "MART", null),
            new SystemTimezoneOptionInfo(423, "Pacific/Midway", "(GMT-11:00) Midway", "UM", "SST", "NDT"),
            new SystemTimezoneOptionInfo(424, "Pacific/Nauru", "(GMT+12:00) Nauru", "NR", "NRT", null),
            new SystemTimezoneOptionInfo(425, "Pacific/Niue", "(GMT-11:00) Niue", "NU", "NUT", null),
            new SystemTimezoneOptionInfo(426, "Pacific/Norfolk", "(GMT+11:30) Norfolk", "NF", "NFT", null),
            new SystemTimezoneOptionInfo(427, "Pacific/Noumea", "(GMT+11:00) Noumea", "NC", "NCT", "NCST"),
            new SystemTimezoneOptionInfo(428, "Pacific/Pago_Pago", "(GMT-11:00) Pago Pago", "AS", "SST", null),
            new SystemTimezoneOptionInfo(429, "Pacific/Palau", "(GMT+09:00) Palau", "PW", "PWT", null),
            new SystemTimezoneOptionInfo(430, "Pacific/Pitcairn", "(GMT-08:00) Pitcairn", "PN", "PST", null),
            new SystemTimezoneOptionInfo(431, "Pacific/Ponape", "(GMT+11:00) Ponape", "FM", "PONT", null),
            new SystemTimezoneOptionInfo(432, "Pacific/Port_Moresby", "(GMT+10:00) Port Moresby", "PG", "PGT", null),
            new SystemTimezoneOptionInfo(433, "Pacific/Rarotonga", "(GMT-10:00) Rarotonga", "CK", "CKT", "CKHST"),
            new SystemTimezoneOptionInfo(434, "Pacific/Saipan", "(GMT+10:00) Saipan", "MP", "ChST", null),
            new SystemTimezoneOptionInfo(435, "Pacific/Tahiti", "(GMT-10:00) Tahiti", "PF", "TAHT", null),
            new SystemTimezoneOptionInfo(436, "Pacific/Tarawa", "(GMT+12:00) Tarawa", "KI", "GILT", null),
            new SystemTimezoneOptionInfo(437, "Pacific/Tongatapu", "(GMT+13:00) Tongatapu", "TO", "TOT", "TOST"),
            new SystemTimezoneOptionInfo(438, "Pacific/Truk", "(GMT+10:00) Truk", "FM", "CHUT", null),
            new SystemTimezoneOptionInfo(439, "Pacific/Wake", "(GMT+12:00) Wake", "UM", "WAKT", null),
            new SystemTimezoneOptionInfo(440, "Pacific/Wallis", "(GMT+12:00) Wallis", "WF", "WFT", null),
            new SystemTimezoneOptionInfo(441, "PST8PDT", null, null, null, null),
        };

        private static IDictionary<short, SystemTimezoneOptionInfo> _timeZonesById;

        public SystemTimezoneOptionInfo(short timezoneId, string olsonName, string displayName, string countryCode,
            string standardAbbr, string daylightAbbr)
        {
            this._timezoneId = timezoneId;
            this._olsonName = olsonName;
            this._displayName = displayName;
            this._countryCode = countryCode;
            this._standardAbbr = standardAbbr;
            this._daylightAbbr = daylightAbbr;
        }

        /// <summary>
        /// Retrieves additional information for the specified time zone option.
        /// </summary>
        /// <param name="type">A system time zone option.</param>
        /// <returns>Additional time zone option information.</returns>
        public static SystemTimezoneOptionInfo Get(SystemTimezoneOption type)
        {
            if (_timeZonesById == null)
            {
                _timeZonesById = new Dictionary<short, SystemTimezoneOptionInfo>();

                foreach (var tz in _timeZones)
                    _timeZonesById[tz.TimezoneId] = tz;
            }

            SystemTimezoneOptionInfo result;
            if (_timeZonesById.TryGetValue((short)type, out result))
                return result;

            return null;
        }

        /// <summary>
        /// Retrieves additional information for the specified time zone option, if
        /// available; otherwise, returns information for America/Chicago.
        /// </summary>
        /// <param name="type">A system time zone option.</param>
        /// <returns>Additional time zone option information.</returns>
        public static SystemTimezoneOptionInfo GetOrDefault(SystemTimezoneOption type)
        {
            return Get(type) ?? Get(SystemTimezoneOption.America_Chicago);
        }

        /// <summary>
        /// Returns all system time zone options' information.
        /// </summary>
        /// <returns>An enumerable of system time zone information.</returns>
        public static IEnumerable<SystemTimezoneOptionInfo> GetAll()
        {
            return _timeZones;
        }
    }
}